name: Continuous integration

on: [pull_request]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Code style
              run: npm run lint

            - name: UI E2E Tests
              run: xvfb-run cypress run --headed --browser chrome --spec 'cypress/e2e/**/*.cy.ts'